import type { IconType } from 'react-icons'
// Sử dụng Font Awesome 5
import {
  FaUtensils,
  FaShoppingBag,
  FaHome,
  FaTaxi,
  FaPills,
  FaRunning,
  FaCar,
  FaHotel,
  FaHeart,
  FaLeaf,
  FaDollarSign,
  FaChartLine,
  FaBriefcase,
  FaGift,
  FaHandHoldingHeart,
  FaEuroSign,
  FaLock,
  FaPlane,
  FaFilm,
  FaMusic,
  FaGamepad,
  FaGlassCheers,
  FaUsers,
  FaShoppingCart,
  FaCamera,
  FaPalette,
  FaCrown,
  FaBook,
  FaCommentDots,
  FaStore,
  FaDog,
  FaBeer,
  FaUsersCog,
  FaCalendarAlt,
  FaLightbulb,
  FaTools,
  FaCoffee,
  FaHamburger,
  FaPizzaSlice,
  FaIceCream,
  FaBirthdayCake,
  FaBaby,
  FaChild,
  FaGraduationCap,
  FaSchool,
  FaUniversity,
  FaStethoscope,
  FaHeartbeat,
  FaHospital,
  FaFirstAid,
  FaShieldAlt,
  FaUmbrella,
  FaBolt,
  FaWater,
  FaWifi,
  FaFire,
  FaBuilding,
  FaGasPump,
  FaParking,
  FaTrain,
  FaBus,
  FaBicycle,
  FaMotorcycle,
  FaShip,
  FaTshirt,
  FaShoePrints,
  FaMobileAlt,
  FaLaptop,
  FaTabletAlt,
  FaDesktop,
  FaHeadphones,
  FaTv,
  FaDice,
  FaSwimmingPool,
  FaMountain,
  FaUmbrellaBeach,
  FaTree,
  FaSeedling,
  FaPaw,
  FaCat,
  FaFish,
  FaHorse,
  FaCreditCard,
  FaWallet,
  FaMoneyBillWave,
  FaCoins,
  FaPiggyBank,
  FaChartBar,
  FaChartPie,
  FaHandshake,
  FaRocket,
  FaStar,
  FaTrophy,
  FaMedal,
  FaAward,
  FaCertificate,
  FaFileInvoice,
  FaReceipt,
  FaEnvelope,
  FaPhone,
  FaVideo,
  FaNewspaper,
  FaGlobe,
  FaLanguage,
  FaFlag,
  FaMapMarkerAlt,
  FaRoute,
  FaCompass,
  FaBinoculars,
  FaHiking,
  FaCampground,
} from 'react-icons/fa'

export type IconOption = {
  id: string
  label: string
  icon: IconType
}

export type IconGroup = {
  id: string
  label: string
  icons: IconOption[]
}

export const CATEGORY_ICON_GROUPS: IconGroup[] = [
  {
    id: 'life',
    label: 'Sinh hoạt',
    icons: [
      { id: 'food', label: 'Ăn uống', icon: FaUtensils },
      { id: 'groceries', label: 'Đi chợ', icon: FaShoppingBag },
      { id: 'coffee', label: 'Cà phê', icon: FaCoffee },
      { id: 'hamburger', label: 'Hamburger', icon: FaHamburger },
      { id: 'pizza', label: 'Pizza', icon: FaPizzaSlice },
      { id: 'ice-cream', label: 'Kem', icon: FaIceCream },
      { id: 'birthday-cake', label: 'Sinh nhật', icon: FaBirthdayCake },
      { id: 'home', label: 'Gia đình', icon: FaHome },
      { id: 'baby', label: 'Em bé', icon: FaBaby },
      { id: 'child', label: 'Trẻ em', icon: FaChild },
      { id: 'transport', label: 'Đi lại', icon: FaTaxi },
      { id: 'car', label: 'Xe cộ', icon: FaCar },
      { id: 'gas-pump', label: 'Xăng dầu', icon: FaGasPump },
      { id: 'parking', label: 'Gửi xe', icon: FaParking },
      { id: 'train', label: 'Tàu hỏa', icon: FaTrain },
      { id: 'bus', label: 'Xe buýt', icon: FaBus },
      { id: 'bicycle', label: 'Xe đạp', icon: FaBicycle },
      { id: 'motorcycle', label: 'Xe máy', icon: FaMotorcycle },
      { id: 'ship', label: 'Tàu thuyền', icon: FaShip },
      { id: 'health', label: 'Sức khỏe', icon: FaPills },
      { id: 'stethoscope', label: 'Khám bệnh', icon: FaStethoscope },
      { id: 'heartbeat', label: 'Tim mạch', icon: FaHeartbeat },
      { id: 'hospital', label: 'Bệnh viện', icon: FaHospital },
      { id: 'first-aid', label: 'Sơ cứu', icon: FaFirstAid },
      { id: 'fitness', label: 'Thể thao', icon: FaRunning },
      { id: 'swimming', label: 'Bơi lội', icon: FaSwimmingPool },
      { id: 'hotel', label: 'Lưu trú', icon: FaHotel },
      { id: 'wellness', label: 'Thư giãn', icon: FaHeart },
      { id: 'greenery', label: 'Cây cảnh', icon: FaLeaf },
      { id: 'tree', label: 'Cây', icon: FaTree },
      { id: 'seedling', label: 'Cây non', icon: FaSeedling },
      { id: 'bolt', label: 'Điện', icon: FaBolt },
      { id: 'water', label: 'Nước', icon: FaWater },
      { id: 'wifi', label: 'Internet', icon: FaWifi },
      { id: 'fire', label: 'Gas', icon: FaFire },
      { id: 'building', label: 'Tòa nhà', icon: FaBuilding },
    ],
  },
  {
    id: 'finance',
    label: 'Tài chính',
    icons: [
      { id: 'salary', label: 'Lương thưởng', icon: FaDollarSign },
      { id: 'investment', label: 'Đầu tư', icon: FaChartLine },
      { id: 'savings', label: 'Tiết kiệm', icon: FaBriefcase },
      { id: 'business', label: 'Kinh doanh', icon: FaBriefcase },
      { id: 'bonus', label: 'Thưởng', icon: FaGift },
      { id: 'charity', label: 'Từ thiện', icon: FaHandHoldingHeart },
      { id: 'stock', label: 'Chứng khoán', icon: FaChartLine },
      { id: 'forex', label: 'Ngoại tệ', icon: FaEuroSign },
      { id: 'safe', label: 'Két sắt', icon: FaLock },
      { id: 'credit-card', label: 'Thẻ tín dụng', icon: FaCreditCard },
      { id: 'wallet', label: 'Ví tiền', icon: FaWallet },
      { id: 'money-bill', label: 'Tiền mặt', icon: FaMoneyBillWave },
      { id: 'coins', label: 'Tiền xu', icon: FaCoins },
      { id: 'piggy-bank', label: 'Ống heo', icon: FaPiggyBank },
      { id: 'chart-bar', label: 'Biểu đồ cột', icon: FaChartBar },
      { id: 'chart-pie', label: 'Biểu đồ tròn', icon: FaChartPie },
      { id: 'handshake', label: 'Hợp đồng', icon: FaHandshake },
      { id: 'file-invoice', label: 'Hóa đơn', icon: FaFileInvoice },
      { id: 'receipt', label: 'Biên lai', icon: FaReceipt },
    ],
  },
  {
    id: 'lifestyle',
    label: 'Giải trí',
    icons: [
      { id: 'travel', label: 'Du lịch', icon: FaPlane },
      { id: 'mountain', label: 'Núi', icon: FaMountain },
      { id: 'beach', label: 'Biển', icon: FaUmbrellaBeach },
      { id: 'hiking', label: 'Leo núi', icon: FaHiking },
      { id: 'camping', label: 'Cắm trại', icon: FaCampground },
      { id: 'compass', label: 'La bàn', icon: FaCompass },
      { id: 'binoculars', label: 'Ống nhòm', icon: FaBinoculars },
      { id: 'route', label: 'Lộ trình', icon: FaRoute },
      { id: 'map-marker', label: 'Địa điểm', icon: FaMapMarkerAlt },
      { id: 'movie', label: 'Xem phim', icon: FaFilm },
      { id: 'tv', label: 'Tivi', icon: FaTv },
      { id: 'music', label: 'Âm nhạc', icon: FaMusic },
      { id: 'headphones', label: 'Tai nghe', icon: FaHeadphones },
      { id: 'gaming', label: 'Game', icon: FaGamepad },
      { id: 'dice', label: 'Cờ bạc', icon: FaDice },
      { id: 'party', label: 'Tiệc tùng', icon: FaGlassCheers },
      { id: 'friends', label: 'Bạn bè', icon: FaUsers },
      { id: 'shopping', label: 'Mua sắm', icon: FaShoppingCart },
      { id: 'tshirt', label: 'Quần áo', icon: FaTshirt },
      { id: 'shoes', label: 'Giày dép', icon: FaShoePrints },
      { id: 'photography', label: 'Nhiếp ảnh', icon: FaCamera },
      { id: 'art', label: 'Nghệ thuật', icon: FaPalette },
      { id: 'vip', label: 'Thành viên VIP', icon: FaCrown },
      { id: 'star', label: 'Ngôi sao', icon: FaStar },
      { id: 'trophy', label: 'Cúp', icon: FaTrophy },
      { id: 'medal', label: 'Huy chương', icon: FaMedal },
      { id: 'award', label: 'Giải thưởng', icon: FaAward },
    ],
  },
  {
    id: 'others',
    label: 'Khác',
    icons: [
      { id: 'education', label: 'Học tập', icon: FaBook },
      { id: 'graduation', label: 'Tốt nghiệp', icon: FaGraduationCap },
      { id: 'school', label: 'Trường học', icon: FaSchool },
      { id: 'university', label: 'Đại học', icon: FaUniversity },
      { id: 'personal', label: 'Cá nhân', icon: FaCommentDots },
      { id: 'mobile', label: 'Điện thoại', icon: FaMobileAlt },
      { id: 'laptop', label: 'Laptop', icon: FaLaptop },
      { id: 'tablet', label: 'Máy tính bảng', icon: FaTabletAlt },
      { id: 'desktop', label: 'Máy tính', icon: FaDesktop },
      { id: 'service', label: 'Dịch vụ', icon: FaStore },
      { id: 'pet', label: 'Thú cưng', icon: FaDog },
      { id: 'cat', label: 'Mèo', icon: FaCat },
      { id: 'fish', label: 'Cá', icon: FaFish },
      { id: 'horse', label: 'Ngựa', icon: FaHorse },
      { id: 'paw', label: 'Chân thú', icon: FaPaw },
      { id: 'gift', label: 'Quà tặng', icon: FaGift },
      { id: 'other', label: 'Khác', icon: FaBeer },
      { id: 'community', label: 'Cộng đồng', icon: FaUsersCog },
      { id: 'event', label: 'Sự kiện', icon: FaCalendarAlt },
      { id: 'idea', label: 'Ý tưởng', icon: FaLightbulb },
      { id: 'maintenance', label: 'Sửa chữa', icon: FaTools },
      { id: 'rocket', label: 'Khởi động', icon: FaRocket },
      { id: 'certificate', label: 'Chứng chỉ', icon: FaCertificate },
      { id: 'envelope', label: 'Thư', icon: FaEnvelope },
      { id: 'phone', label: 'Điện thoại', icon: FaPhone },
      { id: 'video', label: 'Video', icon: FaVideo },
      { id: 'newspaper', label: 'Báo', icon: FaNewspaper },
      { id: 'globe', label: 'Thế giới', icon: FaGlobe },
      { id: 'language', label: 'Ngôn ngữ', icon: FaLanguage },
      { id: 'flag', label: 'Cờ', icon: FaFlag },
      { id: 'umbrella', label: 'Ô', icon: FaUmbrella },
      { id: 'shield', label: 'Bảo vệ', icon: FaShieldAlt },
    ],
  },
]

export const CATEGORY_ICON_MAP = CATEGORY_ICON_GROUPS.reduce<Record<string, IconOption>>((acc, group) => {
  group.icons.forEach((icon) => {
    acc[icon.id] = icon
  })
  return acc
}, {})
